### ISSUE TITLE
Activator template doesn't compile (unresolved dependency: org.ensime#ensime-sbt-cmd;0.1.1)

### ISSUE THREAD

**Issue by tomgreen1** [gigiigig/play-akka-angular-websocket#4]
Hi, I tried to create a project based on this template using typesafe activator-dist-1.3.6. On the initial screen I get an Error: unresolved dependency: org.ensime#ensime-sbt-cmd;0.1.1

Here the complete console output:

Your application is being opened
This will just take a minute...

Template is cloned, compiling project definition...
Loading project definition from H:\progr\workspace\temp2_play-akka-angular-websocket\project
Updating {file:/H:/progr/workspace/temp2_play-akka-angular-websocket/project/}temp2_play-akka-angular-websocket-build...
Resolving play#sbt-plugin;2.1.1 ...
Resolving play#sbt-plugin;2.1.1 ...
[warn] module not found: play#sbt-plugin;2.1.1
module not found: play#sbt-plugin;2.1.1
[warn] ==== typesafe-ivy-releases: tried
==== typesafe-ivy-releases: tried
[warn] https://repo.typesafe.com/typesafe/ivy-releases/play/sbt-plugin/scala_2.10/sbt_0.13/2.1.1/ivys/ivy.xml
https://repo.typesafe.com/typesafe/ivy-releases/play/sbt-plugin/scala_2.10/sbt_0.13/2.1.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
==== sbt-plugin-releases: tried
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/play/sbt-plugin/scala_2.10/sbt_0.13/2.1.1/ivys/ivy.xml
[warn] ==== local: tried
[warn] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/play/sbt-plugin/scala_2.10/sbt_0.13/2.1.1/ivys/ivy.xml
==== local: tried
[warn] C:\Users\tgreen.ivy2\local\play\sbt-plugin\scala_2.10\sbt_0.13\2.1.1\ivys\ivy.xml
C:\Users\tgreen.ivy2\local\play\sbt-plugin\scala_2.10\sbt_0.13\2.1.1\ivys\ivy.xml
[warn] ==== activator-local: tried
==== activator-local: tried
[warn] D:\Programme\activator-dist-1.3.6\repository\play\sbt-plugin\scala_2.10\sbt_0.13\2.1.1\ivys\ivy.xml
D:\Programme\activator-dist-1.3.6\repository\play\sbt-plugin\scala_2.10\sbt_0.13\2.1.1\ivys\ivy.xml
[warn] ==== activator-launcher-local: tried
[warn] C:\Users\tgreen.activator\repository\play\sbt-plugin\scala_2.10\sbt_0.13\2.1.1\ivys\ivy.xml
==== activator-launcher-local: tried
C:\Users\tgreen.activator\repository\play\sbt-plugin\scala_2.10\sbt_0.13\2.1.1\ivys\ivy.xml
==== public: tried
[warn] ==== public: tried
[warn] https://repo1.maven.org/maven2/play/sbt-plugin_2.10_0.13/2.1.1/sbt-plugin-2.1.1.pom
https://repo1.maven.org/maven2/play/sbt-plugin_2.10_0.13/2.1.1/sbt-plugin-2.1.1.pom
[warn] ==== typesafe-releases: tried
==== typesafe-releases: tried
[warn] http://repo.typesafe.com/typesafe/releases/play/sbt-plugin_2.10_0.13/2.1.1/sbt-plugin-2.1.1.pom
http://repo.typesafe.com/typesafe/releases/play/sbt-plugin_2.10_0.13/2.1.1/sbt-plugin-2.1.1.pom
[warn] ==== typesafe-ivy-releasez: tried
==== typesafe-ivy-releasez: tried
[warn] http://repo.typesafe.com/typesafe/ivy-releases/play/sbt-plugin/scala_2.10/sbt_0.13/2.1.1/ivys/ivy.xml
http://repo.typesafe.com/typesafe/ivy-releases/play/sbt-plugin/scala_2.10/sbt_0.13/2.1.1/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
==== Typesafe repository: tried
[warn] http://repo.typesafe.com/typesafe/releases/play/sbt-plugin_2.10_0.13/2.1.1/sbt-plugin-2.1.1.pom
http://repo.typesafe.com/typesafe/releases/play/sbt-plugin_2.10_0.13/2.1.1/sbt-plugin-2.1.1.pom
Resolving org.ensime#ensime-sbt-cmd;0.1.1 ...
Resolving org.ensime#ensime-sbt-cmd;0.1.1 ...
[warn] module not found: org.ensime#ensime-sbt-cmd;0.1.1
module not found: org.ensime#ensime-sbt-cmd;0.1.1
[warn] ==== typesafe-ivy-releases: tried
==== typesafe-ivy-releases: tried
[warn] https://repo.typesafe.com/typesafe/ivy-releases/org.ensime/ensime-sbt-cmd/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
https://repo.typesafe.com/typesafe/ivy-releases/org.ensime/ensime-sbt-cmd/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
==== sbt-plugin-releases: tried
[warn] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.ensime/ensime-sbt-cmd/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.ensime/ensime-sbt-cmd/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
[warn] ==== local: tried
==== local: tried
[warn] C:\Users\tgreen.ivy2\local\org.ensime\ensime-sbt-cmd\scala_2.10\sbt_0.13\0.1.1\ivys\ivy.xml
==== activator-local: tried
[warn] D:\Programme\activator-dist-1.3.6\repository\org.ensime\ensime-sbt-cmd\scala_2.10\sbt_0.13\0.1.1\ivys\ivy.xml
[warn] ==== activator-launcher-local: tried
==== activator-launcher-local: tried
[warn] C:\Users\tgreen.activator\repository\org.ensime\ensime-sbt-cmd\scala_2.10\sbt_0.13\0.1.1\ivys\ivy.xml
C:\Users\tgreen.activator\repository\org.ensime\ensime-sbt-cmd\scala_2.10\sbt_0.13\0.1.1\ivys\ivy.xml
C:\Users\tgreen.ivy2\local\org.ensime\ensime-sbt-cmd\scala_2.10\sbt_0.13\0.1.1\ivys\ivy.xml
==== public: tried
[warn] https://repo1.maven.org/maven2/org/ensime/ensime-sbt-cmd_2.10_0.13/0.1.1/ensime-sbt-cmd-0.1.1.pom
[warn] ==== typesafe-releases: tried
[warn] ==== activator-local: tried
D:\Programme\activator-dist-1.3.6\repository\org.ensime\ensime-sbt-cmd\scala_2.10\sbt_0.13\0.1.1\ivys\ivy.xml
[warn] ==== public: tried
https://repo1.maven.org/maven2/org/ensime/ensime-sbt-cmd_2.10_0.13/0.1.1/ensime-sbt-cmd-0.1.1.pom
http://repo.typesafe.com/typesafe/releases/org/ensime/ensime-sbt-cmd_2.10_0.13/0.1.1/ensime-sbt-cmd-0.1.1.pom
==== typesafe-releases: tried
[warn] http://repo.typesafe.com/typesafe/releases/org/ensime/ensime-sbt-cmd_2.10_0.13/0.1.1/ensime-sbt-cmd-0.1.1.pom
[warn] ==== typesafe-ivy-releasez: tried
==== typesafe-ivy-releasez: tried
[warn] http://repo.typesafe.com/typesafe/ivy-releases/org.ensime/ensime-sbt-cmd/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
http://repo.typesafe.com/typesafe/ivy-releases/org.ensime/ensime-sbt-cmd/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
==== Typesafe repository: tried
[warn] http://repo.typesafe.com/typesafe/releases/org/ensime/ensime-sbt-cmd_2.10_0.13/0.1.1/ensime-sbt-cmd-0.1.1.pom
http://repo.typesafe.com/typesafe/releases/org/ensime/ensime-sbt-cmd_2.10_0.13/0.1.1/ensime-sbt-cmd-0.1.1.pom
Resolving org.scala-lang#scala-library;2.10.4 ...
Resolving org.scala-sbt#sbt;0.13.8 ...
Resolving org.scala-sbt#main;0.13.8 ...
Resolving org.scala-sbt#actions;0.13.8 ...
Resolving org.scala-sbt#classpath;0.13.8 ...
Resolving org.scala-lang#scala-compiler;2.10.4 ...
Resolving org.scala-lang#scala-reflect;2.10.4 ...
Resolving org.scala-sbt#launcher-interface;0.13.8 ...
Resolving org.scala-sbt#interface;0.13.8 ...
Resolving org.scala-sbt#io;0.13.8 ...
Resolving org.scala-sbt#control;0.13.8 ...
Resolving org.scala-sbt#completion;0.13.8 ...
Resolving org.scala-sbt#collections;0.13.8 ...
Resolving jline#jline;2.11 ...
Resolving org.scala-sbt#api;0.13.8 ...
Resolving org.scala-sbt#compiler-integration;0.13.8 ...
Resolving org.scala-sbt#incremental-compiler;0.13.8 ...
Resolving org.scala-sbt#logging;0.13.8 ...
Resolving org.scala-sbt#process;0.13.8 ...
Resolving org.scala-sbt#relation;0.13.8 ...
Resolving org.scala-sbt#compile;0.13.8 ...
Resolving org.scala-sbt#classfile;0.13.8 ...
Resolving org.scala-sbt#persist;0.13.8 ...
Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
Resolving org.scala-sbt#compiler-ivy-integration;0.13.8 ...
Resolving org.scala-sbt#ivy;0.13.8 ...
Resolving org.scala-sbt#cross;0.13.8 ...
Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-fccfbd44c9f64523b61398a0155784dcbaeae28f ...
Resolving com.jcraft#jsch;0.1.46 ...
Resolving org.scala-sbt#serialization_2.10;0.1.1 ...
Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.0 ...
Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
Resolving org.json4s#json4s-core_2.10;3.2.10 ...
Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
Resolving org.scala-sbt#run;0.13.8 ...
Resolving org.scala-sbt#task-system;0.13.8 ...
Resolving org.scala-sbt#tasks;0.13.8 ...
Resolving org.scala-sbt#tracking;0.13.8 ...
Resolving org.scala-sbt#cache;0.13.8 ...
Resolving org.scala-sbt#testing;0.13.8 ...
Resolving org.scala-sbt#test-agent;0.13.8 ...
Resolving org.scala-sbt#test-interface;1.0 ...
Resolving org.scala-sbt#main-settings;0.13.8 ...
Resolving org.scala-sbt#apply-macro;0.13.8 ...
Resolving org.scala-sbt#command;0.13.8 ...
Resolving org.scala-sbt#logic;0.13.8 ...
Resolving org.scala-sbt#compiler-interface;0.13.8 ...
Resolving org.scala-sbt#precompiled-2_8_2;0.13.8 ...
Resolving org.scala-sbt#precompiled-2_9_2;0.13.8 ...
Resolving org.scala-sbt#precompiled-2_9_3;0.13.8 ...
Resolving org.scala-lang#jline;2.10.4 ...
Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: UNRESOLVED DEPENDENCIES ::
:: UNRESOLVED DEPENDENCIES ::
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: play#sbt-plugin;2.1.1: not found
:: play#sbt-plugin;2.1.1: not found
[warn] :: org.ensime#ensime-sbt-cmd;0.1.1: not found
:: org.ensime#ensime-sbt-cmd;0.1.1: not found
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] Note: Some unresolved dependencies have extra attributes. Check that these dependencies exist with the requested attributes.
Note: Some unresolved dependencies have extra attributes. Check that these dependencies exist with the requested attributes.
[warn] play:sbt-plugin:2.1.1 (scalaVersion=2.10, sbtVersion=0.13)
play:sbt-plugin:2.1.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn] org.ensime:ensime-sbt-cmd:0.1.1 (scalaVersion=2.10, sbtVersion=0.13)
org.ensime:ensime-sbt-cmd:0.1.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] Note: Unresolved dependencies path:
Note: Unresolved dependencies path:
[warn] play:sbt-plugin:2.1.1 (scalaVersion=2.10, sbtVersion=0.13) (H:\progr\workspace\temp2_play-akka-angular-websocket\project\plugins.sbt#L8-9)
play:sbt-plugin:2.1.1 (scalaVersion=2.10, sbtVersion=0.13) (H:\progr\workspace\temp2_play-akka-angular-websocket\project\plugins.sbt#L8-9)
[warn] +- default:temp2_play-akka-angular-websocket-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
+- default:temp2_play-akka-angular-websocket-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] org.ensime:ensime-sbt-cmd:0.1.1 (scalaVersion=2.10, sbtVersion=0.13) (H:\progr\workspace\temp2_play-akka-angular-websocket\project\plugins.sbt#L10-11)
org.ensime:ensime-sbt-cmd:0.1.1 (scalaVersion=2.10, sbtVersion=0.13) (H:\progr\workspace\temp2_play-akka-angular-websocket\project\plugins.sbt#L10-11)
[warn] +- default:temp2_play-akka-angular-websocket-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
+- default:temp2_play-akka-angular-websocket-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
unresolved dependency: play#sbt-plugin;2.1.1: not found unresolved dependency: org.ensime#ensime-sbt-cmd;0.1.1: not found
sbt.ResolveException: unresolved dependency: play#sbt-plugin;2.1.1: not found
unresolved dependency: org.ensime#ensime-sbt-cmd;0.1.1: not found
at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
at xsbt.boot.Using$.withResource(Using.scala:10)
at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
at xsbt.boot.Locks$.apply0(Locks.scala:31)
at xsbt.boot.Locks$.apply(Locks.scala:28)
at sbt.IvySbt.withIvy(Ivy.scala:127)
at sbt.IvySbt.withIvy(Ivy.scala:124)
at sbt.IvySbt$Module.withModule(Ivy.scala:155)
at sbt.IvyActions$.updateEither(IvyActions.scala:165)
at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
at sbt.std.Transform$$anon$4.work(System.scala:63)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
at xsbt.boot.Using$.apply(Using.scala:9)
at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
at sbt.Execute.work(Execute.scala:235)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[error](*:update) sbt.ResolveException: unresolved dependency: play#sbt-plugin;2.1.1: not found
[error] unresolved dependency: org.ensime#ensime-sbt-cmd;0.1.1: not found
(*:update) sbt.ResolveException: unresolved dependency: play#sbt-plugin;2.1.1: not found unresolved dependency: org.ensime#ensime-sbt-cmd;0.1.1: not found
Failed to load project.

**Comment by alanbraz** [comment]
same here!

**Comment by addict3d** [comment]
I'm trying the same thing as you, also using typesafe activator-dist-1.3.6. I have no clue what I'm doing when it comes to scala and sbt.

I think the versions of play sbt-plugin and ensime-sbt-cmd are outdated. I'm not sure how to get the code and projected template updated to work but will give it a try. Any guidance would be appreciated.

**Comment by gigiigig** [comment]
Hi guys, thanks for the report, 
it looks like activator is downloading an older version of the repository, 
if you clone in from github and run with sbt it is working. 

I'll try to see why this happens.

**Comment by sakar-sr** [comment]
Missing build.sbt file. please include the build file
